ALTER TABLE [dbo].[Fins]
    ADD CONSTRAINT [PK_Fins] PRIMARY KEY CLUSTERED ([FinId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

