ALTER TABLE [dbo].[KiteBoards]
    ADD CONSTRAINT [PK_KiteBoards] PRIMARY KEY CLUSTERED ([KiteboardId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

