ALTER TABLE [dbo].[Kites]
    ADD CONSTRAINT [PK_Kites] PRIMARY KEY CLUSTERED ([KiteId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

