ALTER TABLE [dbo].[Rigs]
    ADD CONSTRAINT [PK_Rigs] PRIMARY KEY CLUSTERED ([RigId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

