ALTER TABLE [dbo].[Snowboards]
    ADD CONSTRAINT [PK_Snowboards] PRIMARY KEY CLUSTERED ([SnowboardId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

