ALTER TABLE [dbo].[Venues]
    ADD CONSTRAINT [PK_Venues] PRIMARY KEY CLUSTERED ([VenueId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

